[package]
name = "emu"
version = "0.1.0"
authors = ["joachim <you@example.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.*"